[[language]]
name = "rust"
file-types = ["rs"]
config.check.command = "clippy"

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
file-types = ["html"]

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
file-types = ["json"]

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
file-types = ["css"]

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
file-types = ["js"]

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
file-types = ["ts"]
