# ████████╗███╗   ███╗██╗   ██╗██╗  ██╗    ██████╗ ██████╗ ███╗   ██╗███████╗
# ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝   ██╔════╝██╔═══██╗████╗  ██║██╔════╝
#    ██║   ██╔████╔██║██║   ██║ ╚███╔╝    ██║     ██║   ██║██╔██╗ ██║█████╗
#    ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗    ██║     ██║   ██║██║╚██╗██║██╔══╝
#    ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗██╗╚██████╗╚██████╔╝██║ ╚████║██║
#    ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝

# changing the command button to C-z
unbind C-b
set -g prefix M-z
bind Space send-prefix

# Using the mouse
set -g mouse on

# Vertical split with g or C-g
unbind g
unbind C-g
bind-key g split-window -h
bind-key C-g split-window -h

# Horizontal split with h or C-h
unbind h
unbind C-h
bind-key h split-window
bind-key C-h split-window

# quiting a pane 
bind -n M-q kill-window
# bind-key r source-file ~/.tmux.conf
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'toddyamakawa/tmux-prefixless'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'olimorris/tmux-pomodoro-plus'

# dracula config
# Fix: Ensure kubeconfig and git plugins are correctly configured
set -g @dracula-plugins 'battery git kubernetes-context'
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-empty-plugins false
set -g @dracula-military-time false
set -g @dracula-show-left-icon "#S#{?#(cat /tmp/pomodoro/current_status.txt 2>/dev/null | grep -q 'in_progress' && echo 1), | #{pomodoro_status},}"

# Pomodoro config
set -g @pomodoro_mins 25
set -g @pomodoro_break_mins 5
set -g @pomodoro_on "#[fg=$text_red]🍅 "
set -g @pomodoro_complete "#[fg=$text_green]✅ "
set -g @pomodoro_pause "#[fg=$color_yellow]⏸︎ "
set -g @pomodoro_prompt_break "#[fg=$color_green]🕤 ? "
set -g @pomodoro_prompt_pomodoro "#[fg=$color_gray]🕤 ? "
set -g @pomodoro_notifications 'on'
set -g @pomodoro_sound 'on'
set -g @pomodoro_granularity 'on'
set -g @pomodoro_menu_position "R"
set -g status-interval 2

# Git plugin settings
set -g @dracula-git-show-current-symbol ✓
set -g @dracula-git-show-diff-symbol !

# Kubernetes plugin settings - Ensure it checks for current kubeconfig
set -g @dracula-kubernetes-context-label 'k8s'
set -g @dracula-kubernetes-context-colors 'cyan dark_gray'

run '~/.tmux/plugins/tpm/tpm'
