return function()
	local lspconfig = require('lspconfig')
	require('config.lsp.mason')

	lspconfig.bashls.setup({})
	lspconfig.clangd.setup({})
	lspconfig.elixirls.setup({})
	lspconfig.grammarly.setup({})
	lspconfig.jsonls.setup({})
	lspconfig.lua_ls.setup({ diagnostics = { globals = { 'vim' } } })
	lspconfig.phpactor.setup({})
	lspconfig.pyright.setup({})
	lspconfig.ruby_ls.setup({})
	lspconfig.tsserver.setup({})
	lspconfig.emmet_language_server.setup({})

	require('config.lsp.mason')
	require('config.lsp.handlers').setup()
	require('config.lsp.go')
	require('config.lsp.rust')
end
