local lspconfig = require('lspconfig')
lspconfig.bashls.setup({})
lspconfig.clangd.setup({})
lspconfig.gopls.setup({})
lspconfig.lua_ls.setup({ diagnostics = { globals = { 'vim' } } })
lspconfig.pyright.setup({})
lspconfig.ruby_ls.setup({})
lspconfig.rust_analyzer.setup({})
lspconfig.grammarly.setup({})
lspconfig.phpactor.setup({})

require('config.lsp.mason')
require('config.lsp.null-ls')
require('config.lsp.handlers').setup()
