#!/usr/bin/env bash

bspc monitor HDMI-A-1 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 1 2 3 4 5 
bspc monitor -d I II III IV V VI VII VIII VX X 

bspc config border_width			0
bspc config window_gap				9

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config focused_border_color	"#BD93F9"
bspc config normal_border_color		"#282A36"
bspc config active_border_color		"#8BE9FD"
bspc config presel_feedback_color	"#50FA7B"

# ~/.fehbg &
feh --no-fehbg --bg-fill --randomize ~/Wallpapers/** &
sxhkd &
polybar &
picom &
dunst &
killall flameshot && flameshot &
xss-lock --transfer-sleep-lock -- i3lock --nofork -e -f -c "#000000"
setxkbmap -layout us,ar -option grp:win_space_toggle
