require('config.themes.catppuccin')
require('config.themes.dracula')
require('config.themes.github')
require('config.themes.nightfox')
require('config.themes.nord')
require('config.themes.onedark')
require('config.themes.onenord')
-- require('config.themes.rose-pine')
require('config.themes.tokyonight')
